In [84]:
import numpy as np
import pandas as pd

data_file = "purchase_data.json"
df = pd.read_json(data_file)
df

,Age,Gender,Item ID,Item Name,Price,SN
0,20,Male,93,Apocalyptic Battlescythe,4.49,Iloni35
1,21,Male,12,Dawne,3.36,Aidaira26
2,17,Male,5,Putrid Fan,2.63,Irim47
3,17,Male,123,Twilight's Carver,2.55,Irith83
4,22,Male,154,Feral Katana,4.11,Philodil43
5,8,Male,8,"Purgatory, Gem of Regret",2.22,Hainaria90
6,40,Male,148,"Warmonger, Gift of Suffering's End",4.65,Aerithllora36
7,28,Male,27,"Riddle, Tribute of Ended Dreams",3.38,Undirra90
8,18,Male,111,Misery's End,1.79,Eolideu96
9,36,Male,139,"Mercy, Katana of Dismay",4.25,Aesurstilis64
10,24,Male,126,Exiled Mithril Longsword,1.08,Jiskimsda56
11,36,Female,173,Stormfury Longsword,4.01,Jiskim75
12,20,Female,90,Betrayer,4.12,Lirtassa77
13,32,Male,23,Crucifer,1.62,Hairith93
14,8,Male,44,Bonecarvin Battle Axe,4.36,Yarith71
15,23,Male,94,Mourning Blade,3.64,Sondim43
16,24,Male,174,Primitive Blade,1.36,Zhisrisu83
17,9,Male,156,Soul-Forged Steel Shortsword,4.53,Rarallo90
18,12,Other / Non-Disclosed,176,Relentless Iron Skewer,2.12,Inadeu25
19,23,Male,154,Feral Katana,4.11,Haerithp41
20,35,Male,10,Sleepwalker,1.81,Streural92
21,11,Male,131,Fury,2.99,Eoralphos86
22,16,Male,172,Blade of the Grave,2.71,Shaidanu32
23,20,Male,158,"Darkheart, Butcher of the Champion",1.94,Lassimla92
24,23,Male,70,Hope's End,4.28,Heosurnuru52
25,17,Male,71,Demise,3.09,Ilara98
26,7,Male,98,"Deadline, Voice Of Subtlety",1.29,Lirtistanya48
27,25,Male,117,"Heartstriker, Legacy of the Light",4.71,Sundaky74
28,20,Female,170,Shadowsteel,1.74,Sondassasya91
29,21,Male,90,Betrayer,4.12,Arithllorin55
...,...,...,...,...,...,...
48,25,Male,84,Arcane Gem,4.81,Eusty71
49,20,Male,14,Possessed Core,2.82,Frichilsa31
50,23,Male,176,Relentless Iron Skewer,2.12,Filon68
51,28,Male,1,Crucifer,3.67,Palyon91
52,23,Female,118,"Ghost Reaver, Longsword of Magic",2.95,Assistast50
53,16,Female,94,Mourning Blade,3.64,Seostylis96
54,25,Male,111,Misery's End,1.79,Iskadar31
55,20,Male,108,"Extraction, Quickblade Of Trembling Hands",2.26,Pheodaisun84
56,17,Male,79,"Alpha, Oath of Zeal",1.31,Yarmol79
57,23,Female,107,"Splitter, Foe Of Subtlety",4.15,Aeri79
58,30,Female,105,Hailstorm Shadowsteel Scythe,1.02,Undosian34
59,39,Female,2,Verdict,2.65,Aesririam61
60,23,Female,68,"Storm-Weaver, Slayer of Inception",4.39,Firon67
61,21,Male,31,Trickster,4.59,Jiskjask76
62,18,Male,25,Hero Cane,4.78,Chanirra64
63,11,Female,41,Orbit,3.85,Isristira52
64,24,Male,164,Exiled Doomblade,1.31,Chaniman66
65,23,Male,181,Reaper's Toll,4.12,Yarithrgue83
66,24,Male,4,Bloodlord's Fetish,1.91,Airi27
67,22,Male,94,Mourning Blade,3.64,Undilsan50
68,21,Male,82,Nirvana,1.77,Aidaira26
69,34,Male,126,Exiled Mithril Longsword,1.08,Chamalo71
70,25,Male,98,"Deadline, Voice Of Subtlety",1.29,Undadar97
71,25,Male,60,Wolf,2.70,Sundaky74
72,21,Male,180,Stormcaller,2.77,Lisirra44
73,35,Male,93,Apocalyptic Battlescythe,4.49,Chamast86
74,38,Male,163,Thunderfury Scimitar,4.16,Ardcil81
75,15,Male,167,"Malice, Legacy of the Queen",3.25,Heudai45
76,24,Male,97,"Swan Song, Gouger Of Terror",1.92,Chaniman66
77,20,Male,134,Undead Crusader,2.15,Syalallodil59

In [85]:
#Player Count

count = df["Gender"].value_counts()
count

Player_count = pd.DataFrame({"Player Count":count})
Player_count

                       Player Count
Male                             64
Female                           13
Other / Non-Disclosed             1

In [86]:
#Total Number of Players
total = df["Item ID"].count()
total

total_number_of_players = pd.DataFrame({"Total Number of Players":[total]})
total_number_of_players

   Total Number of Players
0                       78

In [87]:
#Purchasing Analysis (Total)
#Number of Unique Items
#Average Purchase Price
#Total Number of Purchases
#Total Revenue
Unique_Items = len(df["Item Name"].unique())
Average_Price = df["Price"].mean()
Total_Purchases = df["Price"].count()
Total_Revenue = df["Price"].sum()


Purchasing_Analysis = pd.DataFrame({"Number of Unique Items":Unique_Items,
                                    "Average Purchase Price":[Average_Price],
                                    "Total Number of Purchases":[Total_Purchases],
                                    "Total Revenue":[Total_Revenue]})
Purchasing_Analysis = Purchasing_Analysis.round(2)
Purchasing_Analysis

,Average Purchase Price,Number of Unique Items,Total Number of Purchases,Total Revenue
0,2.92,63,78,228.1

In [88]:
Purchasing_Analysis ["Average Purchase Price"] = Purchasing_Analysis["Average Purchase Price"].map("${:,.2f}".format)
Purchasing_Analysis ["Total Number of Purchases"] = Purchasing_Analysis["Total Number of Purchases"].map("{:,}".format)
Purchasing_Analysis ["Total Revenue"] = Purchasing_Analysis["Total Revenue"].map("${:,.2f}".format)
Purchasing_Analysis = Purchasing_Analysis.loc[:,["Number of Unique Items","Average Purchase Price","Total Number of Purchases","Total Revenue"]]
Purchasing_Analysis

,Number of Unique Items,Average Purchase Price,Total Number of Purchases,Total Revenue
0,63,$2.92,78,$228.10

In [89]:
#Gender Demographics
#Percentage and Count of Male Players
#Percentage and Count of Female Players
#Percentage and Count of Other / Non-Disclosed

Gender_Demographics = df["Gender"].value_counts()
Percentage_Gender_Demographics = Gender_Demographics / total*100
Gender_Demographics = pd.DataFrame({"Total Count": Gender_Demographics,"Percentage of Players":Percentage_Gender_Demographics})
Gender_Demographics = Gender_Demographics.round(2)
#Gender_Demographics = Gender_Demographics..map("%{:,.2f}".format)
Gender_Demographics

                       Percentage of Players  Total Count
Male                                   82.05           64
Female                                 16.67           13
Other / Non-Disclosed                   1.28            1

In [90]:
#Purchasing Analysis (Gender)
#The below each broken by gender
#Purchase Count
#Average Purchase Price
#Total Purchase Value
#Normalized Totals

gender_Table = df.groupby(["Gender"])["Price"].count()
average_puchase_price = df.groupby(["Gender"])["Price"].mean()
total_purchase_value = df.groupby(["Gender"])["Price"].sum()
normalize_totals = gender_Table/total_purchase_value.count()

average_puchase_price = average_puchase_price.map("${:,.2f}".format)
total_purchase_value = total_purchase_value.map("${:,.2f}".format)
normalize_totals = normalize_totals.map("${:,.2f}".format)

purchasing_Analysis_Gender_Table = pd.DataFrame({"Purchase Count": Gender_Table,"Average Purchase Price":average_puchase_price,"Total Purchase Value":total_purchase_value,"Normalize Totals":normalize_totals})
purchasing_Analysis_Gender_Table = purchasing_Analysis_Gender_Table.round(2)

purchasing_Analysis_Gender_Table

,Average Purchase Price,Normalize Totals,Purchase Count,Total Purchase Value
Gender,,,,
Female,$3.18,$4.33,13,$41.38
Male,$2.88,$21.33,64,$184.60
Other / Non-Disclosed,$2.12,$0.33,1,$2.12

In [107]:
#Age Demographics
#The below each broken into bins of 4 years (i.e. <10, 10-14, 15-19, etc.)
age_column = df.iloc[:,0:1]
age_column

#age_max = df["Age"].max()
#age_max

bins_of_four_years = ["< 10"," 10 - 14", " 15 - 19", "20 - 24", "25 - 29", " 30 - 34", "35 - 39", " 40 +"]
age_by_ranges = [0, 9.90,14.90,19.90,24.90,29.90,34.90,39.90, 99999]
age_by_ranges

bins_of_four_years

age_demographics = pd.cut(df["Age"], age_by_ranges, labels = bins_of_four_years)
age_demographics



#Age_Purchase_Count= df["Age"].value.counts()
#Average Purchase Price
#Total Purchase Value
#Normalized Totals



#"Total Purchase Value": sales_data['Price'],
#    "Normalized Totals": sales_data['Price']})
        
#def agerange_func(row):
#    if row['Age'] < [10]:
  #      val = "<10"
#    elif(row['Age'] >=[10]) & (row['Age'] <[14]):
 #       val = "10-14"
#    elif(row['Age'] >=[15]) & (row['Age'] <[19]):
#        val = "15-19"   
#    elif(row['Age'] >=[20]) & (row['Age'] <[24]):
#        val = "20-24"  
#    elif(row['Age'] >=[25]) & (row['Age'] <[29]):
   #     val = "25-29"  
    #elif(row['Age'] >=[30]) & (row['Age'] <[34]):
     #   val = "30-34"  
    #elif(row['Age'] >=[35]) & (row['Age'] <[39]):
     #   val = "35-39"  
    #else:
     #   val = "40+"  
    #return val

#age_column = age_column.apply(agerange_func, axis=1)
#age_column
#merge_table = pd.merge(age_column,df, on = "Age")
#merge_table


#Purchase_Count = age_column.groupby(["Age"])["Total Purchase Value"].count()
#Purchase_Count
#Average_Purchase_Price_Age = age_column.groupby(["Age"])["Total Purchase Value"].mean()
#Total_Purchase_Value = age_column.groupby(["Age"])["Total Purchase Value"].sum()
#Normalized_Totals = Average_Purchase_Price_Age /Total_Purchase_Value


#age_demographics=pd.DataFrame({"Purchase Count": Purchase_Count,
#                                "Average Purchase Price": Average_Purchase_Price_Age,
#                                "Total Purchase Value": Total_Purchase_Value,
#                                "Normalized Totals": Normalized_Totals})

#age_demographics

#Total_Purchases
#Purchase Count
#Average Purchase Price
#Total Purchase Value
#Normalized Totals




#reduced_kickstarter_df = df.["Age"] < 10

#df.loc[(df["Age"] < 10)]
#reduced_kickstarter_df

#df1.merge(df2 on="col").merge(df3 on "col")

0      20 - 24
1      20 - 24
2      15 - 19
3      15 - 19
4      20 - 24
5         < 10
6         40 +
7      25 - 29
8      15 - 19
9      35 - 39
10     20 - 24
11     35 - 39
12     20 - 24
13     30 - 34
14        < 10
15     20 - 24
16     20 - 24
17        < 10
18     10 - 14
19     20 - 24
20     35 - 39
21     10 - 14
22     15 - 19
23     20 - 24
24     20 - 24
25     15 - 19
26        < 10
27     25 - 29
28     20 - 24
29     20 - 24
        ...
48     25 - 29
49     20 - 24
50     20 - 24
51     25 - 29
52     20 - 24
53     15 - 19
54     25 - 29
55     20 - 24
56     15 - 19
57     20 - 24
58     30 - 34
59     35 - 39
60     20 - 24
61     20 - 24
62     15 - 19
63     10 - 14
64     20 - 24
65     20 - 24
66     20 - 24
67     20 - 24
68     20 - 24
69     30 - 34
70     25 - 29
71     25 - 29
72     20 - 24
73     35 - 39
74     35 - 39
75     15 - 19
76     20 - 24
77     20 - 24
Name: Age, Length: 78, dtype: category
Categories (8, object): [10 - 14 < 15 - 19 < 30 - 34 < 40 + < 20 - 24 < 25 - 29 < 35 - 39 < < 10]

In [ ]:
#Purchasing_Analysis.to_csv("../Output/Purchasing_Analysis.csv")